Выполнила домашнее задание - графика всех страниц
htmlacademy-htmlcss/1664451-device-30 pull request #4
Opened 2021-02-04 18:15 UTC by GutaShuhart

Добавила контентные изображения

2021-02-04 18:16 UTC, GutaShuhart commented on catalog.html
> +      <a href="index.html"><img src="img/device-logo-black.svg" width="163" height="35" alt="Логотип магазина Device">
Добавила лого в формате SVG,  но насколько я понимаю такой простой логотип можно сделать просто шрифтом?

2021-02-04 18:19 UTC, GutaShuhart commented on catalog.html
>              <a href="Селфи-палка-Следуй-за-мной».html">
Не уверена, что в каталоге нужно было прописывать alt к изображению. Так как описание совпадает с подписью к карточке.

2021-02-04 18:20 UTC, GutaShuhart reviewed
Пара вопросов по изображениям.

2021-02-05 08:21 UTC, kamunicorn commented on catalog.html
>              <a href="Селфи-палка-Следуй-за-мной».html">
alt должен быть по требованиям, он не всегда будет совпадать с подписью

2021-02-05 08:43 UTC, kamunicorn commented on catalog.html
> +      <a href="index.html"><img src="img/device-logo-black.svg" width="163" height="35" alt="Логотип магазина Device">
Проще сделать на svg - не надо подгонять под pixel perfect и делать дополнительную стилизацию. А можно ли по правилам интенсива - я лучше уточню этот вопрос.

2021-02-05 08:59 UTC, kamunicorn requested changes
добавить изображения в папку img

2021-02-05 08:59 UTC, kamunicorn commented on index.html
> +          src="img/content/map.jpg" width="560" height="222" alt="Карта офиса по адресу улица Строителей, 15"></a>
Нужно добавить модальное окно с картой (в конце, где остальные модалки).

2021-02-05 09:22 UTC, kamunicorn commented on catalog.html
> +      <a href="index.html"><img src="img/device-logo-black.svg" width="163" height="35" alt="Логотип магазина Device">
Даже тогда, когда можно технически повторить логотип через текст — это обычно отдельный шритф, а значит отдельный запрос на специально подготовленный сабсетом (в лучшем случае) шрифт, который всё равно будет весить больше, чем обычный svg с обычным path (просто из-за кучи технической информации о метриках шрифта зашитых в файл этого шрифта). Ну и каждое из возможных сочетаний браузерных движков и ОСей — это отдельные вариации рендеринга глифов, их взаимного расположения, сглаживания, хинтинга и прочего.
Это всё не в пользу того, когда надо передать максимально чётко фирменный стиль, а логотип — одна из важнейших частей любого фирменного стиля.
Кроме того во время загрузки шрифта, лого будет написано сначала одним шрифтом, и уже потом своим, а многим заказчикам это просто не понравится.

2021-02-05 09:27 UTC, kamunicorn commented on index.html
>    <footer>
Нужны картинки логотипов соцсетей - они тоже контентные изображения.

2021-02-05 10:03 UTC, kamunicorn requested changes
добавить изображения в папку img

2021-02-06 07:42 UTC, kamunicorn commented on catalog.html
>              <a href="Селфи-палка-Следуй-за-мной».html">
Вот кстати еще почему нужен alt: при поиске alt считывается и картинка показывается в результатах поиска, после чего пользователь может перейти на страницу с этой картинкой.

2021-02-08 10:48 UTC, kamunicorn commented on catalog.html
> +          <a href="#"><img src="img/icon-facebook.png" width="32" height="32" alt="Логотип социальной сети Фейсбук">Фейсбук</a>
В этом случае alt лучше назвать просто по названию компании. Это делается для того, чтобы при отключенной картинке показывалось название компании.
![image](https://user-images.githubusercontent.com/38280676/107207477-d3ed1e80-6a5c-11eb-94ce-77e2369d904f.png)
вот так будет выглядеть картинка, если не загрузится

2021-02-08 10:48 UTC, kamunicorn commented on img/logo-dji.svg
> +<svg width="260" height="100" viewBox="0 0 260 100" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
Эти логотипы ненастоящие svg (еще и весят больше, чем png или jpg). Еще при наведении они становятся яркими, но это не значит, что нужно две картинки, можно сделать это с помощью css-фильтра - надо использовать исходную яркую картинку.

2021-02-08 10:56 UTC, merged