Выполнила задание 4.18  Стилизация главной страницы
htmlacademy-htmlcss/1664451-device-30 pull request #5
Opened 2021-02-10 20:36 UTC by GutaShuhart

2021-02-11 03:40 UTC, kamunicorn reviewed
Соблюдены почти все важные критерии, кроме Б10 (разберем на консультации как и зачем это делается), Б15 (немного подровнять отступы в style.css). В таблице стилей кастомные свойства с цветами задекларированы, но не используются. Есть замечания по поводу именования классов - не всегда понятно, за какой элемент отвечает данный класс, или используются значения css-правил в качестве названия класса (uppercase).

2021-02-11 03:40 UTC, kamunicorn commented on css/style.css
> +.number{
Если смотреть файл стилей оторванно от html или веб-страницы в браузере не совсем понятно, что это за число и где оно находится.

2021-02-11 03:40 UTC, kamunicorn commented on css/style.css
> +.selected-text{
Тут тоже непонятно, что это за выделенный текст (если перевести). Ни за что бы не догадалась, что это список.

2021-02-11 03:40 UTC, kamunicorn commented on css/style.css
> +.search-button-hover:hover{
Дублирование классов: уже есть класс .search-button, для эффекта ховера ему достаточно добавить псевдокласс :hover (и для фокуса то же самое)

2021-02-11 03:40 UTC, kamunicorn commented on index.html
> +        <li class="services"> <a class="focus" href="blank.html">  <!-- не пойму почему фокус не работает-->
Можешь добавить тут сразу картинки, чтобы нагляднее видеть как применяются эффекты.

2021-02-11 09:37 UTC, kamunicorn commented on index.html
>        <h2>Контакты</h2>
и тут нет класса

2021-02-11 09:37 UTC, kamunicorn commented on index.html
>        <h2>О нас</h2>
тут нет класса

2021-02-14 10:18 UTC, kamunicorn requested changes
Есть замечания, требующие доработок, по части эффектов наведения и нажатия.
Комментарии с приставкой "не критично" не требуют немедленных изменений к следующему дз.

2021-02-14 10:18 UTC, kamunicorn commented on css/style.css
> + color:var(--basic-white);
Нет эффекта наведения, когда убирается непрозрачность.
Причем, в этом пункте меню присутствует иконка, которая ведет себя противоположным образом к тексту ссылки. Похожая ситуация в секции популярных товаров. Декоративную графику вы будете добавлять потом, но учесть ее существование желательно уже сейчас.

2021-02-14 10:18 UTC, kamunicorn commented on index.html
>        <button class="button-closed" type="button">Закрыть</button>
Тут тоже добавить фоновый цвет и эффекты, причем иконка, которая будет внутри кнопки, не должна менять своих параметров во время эффектов.

2021-02-14 15:23 UTC, GutaShuhart commented on img/background-services.svg
> +<svg width="160" height="160" viewBox="0 0 160 160" fill="none" xmlns="http://www.w3.org/2000/svg">
Нет, я забыла, что в итоге параметры фона через CSS задала.

2021-02-14 16:03 UTC, GutaShuhart commented on css/style.css
> + color:var(--basic-white);
Эффект наведения добавила, но не пойму как учесть, то чего нет? Стили прописать? А к чему их?

2021-02-15 00:30 UTC, merged

2021-02-15 08:36 UTC, GutaShuhart commented on css/style.css
> +  color:var(--basic-black);
Когда поставила font:inherit все ссылки стали фиолетовые

2021-02-16 23:50 UTC, kamunicorn commented on css/style.css
> +  color:var(--basic-black);
font задает только параметры шрифта, но не color. Если прописать еще и color: inherit, то цвет ссылки будет как у родителя