Прописала стили в каталоге
htmlacademy-htmlcss/1664451-device-30 pull request #6
Opened 2021-02-17 08:44 UTC by GutaShuhart

Исправила ошибки в главной странице

2021-02-17 11:03 UTC, kamunicorn requested changes
По части разметки и названий классов в целом все хорошо (на обоих страницах). Классы присутствуют почти везде, где надо, и понятно за что они отвечают.
В паре мест придется поменять или добавить классы, чтобы удобнее было стилизовать в будущем.
Увидеть какие-то изменения в стилизации не могу, т.к. не загружен обновленный файл стилей (последний 4-хдневной давности).

2021-02-17 11:03 UTC, kamunicorn commented on catalog.html
> -        <p><input type="search" name="q" placeholder="Поиск по сайту">
p тут лишняя обертка по критерию Д2, достаточно будет и form

2021-02-17 12:04 UTC, kamunicorn reviewed
Исправлены все замечания к главной странице, к внутренней странице есть пара совсем маленьких заметок.

2021-02-17 12:04 UTC, kamunicorn commented on css/style.css
> +  background-color:var(--special-yellow-dark);
Полосочку посередине можно сделать через псевдоэлемент (after, before) и позиционирование относительно родителя (кнопка) - это из материалов раздела 7.

2021-02-21 06:12 UTC, GutaShuhart commented on css/style.css
> +  background-color:var(--special-yellow-dark);
Ок.Переделаю как дойду.

2021-02-21 08:52 UTC, merged